### ISSUE TITLE
Error: Error loading state: 2 problems:

### ISSUE THREAD

**Issue by longtran84** [ssakhamuri/spring-boot-aws-lambda-terraform#3]
Error: Error loading state: 2 problems:

- Unsupported state file format: The state file could not be parsed as JSON: syntax error at byte offset 1.
- Unsupported state file format: The state file does not have a "version" attribute, which is required to identify the format version.

**Comment by ssakhamuri** [comment]
> Error: Error loading state: 2 problems:
> 
> * Unsupported state file format: The state file could not be parsed as JSON: syntax error at byte offset 1.
> * Unsupported state file format: The state file does not have a "version" attribute, which is required to identify the format version.

Fixed. Thanks
